# Generated by Django 3.0.8 on 2020-08-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='height_cm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
