# Generated by Django 3.0.7 on 2020-07-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='verstat',
            field=models.CharField(default='', max_length=20),
        ),
    ]
