# Generated by Django 3.0.8 on 2020-08-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200801_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='height_cm',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='weight',
            field=models.CharField(max_length=50),
        ),
    ]
